version: "3.9"

services:
  backend:
    image: redhatcsaweb-backend
    container_name: backend
    ports:
      - "5051:5051"
    environment:
      PROXMOX_USER: "${PROXMOX_USER}"
      PROXMOX_PASSWORD: "${PROXMOX_PASSWORD}"
      TEMPLATE1: "${TEMPLATE1}"
      TEMPLATE2: "${TEMPLATE2}"
      TEMPLATE3: "${TEMPLATE3}"

  frontend:
    image: redhatcsaweb-frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
