services:
  backend:
    build:
      context: ./backend # path to your backend Dockerfile
    ports:
      - "5051:5051"
    environment:
      PROXMOX_USER: "${PROXMOX_USER}"
      PROXMOX_PASSWORD: "${PROXMOX_PASSWORD}"
      TEMPLATE1: "${TEMPLATE1}"
      TEMPLATE2: "${TEMPLATE2}"
      TEMPLATE3: "${TEMPLATE3}"

  frontend:
    build:
      context: ./frontend # path to your frontend Dockerfile
    container_name: rhcsa-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
