services:
  backend:
    container_name: rhcsa-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      Proxmox__Templates__Server1: "${PROXMOX__TEMPLATES__SERVER1}"
      Proxmox__Templates__Server2: "${PROXMOX__TEMPLATES__SERVER2}"
      Proxmox__Host: "${PROXMOX__HOST}"
      Proxmox__Node: "${PROXMOX__NODE}"
      Proxmox__ApiToken: "${PROXMOX__APITOKEN}"
      Proxmox__Username: "${PROXMOX__USERNAME}"
      Proxmox__Password: "${PROXMOX__PASSWORD}"
    networks:
      rhcsa-net:
        ipv4_address: 172.20.0.2

  frontend:
    container_name: rhcsa-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      rhcsa-net:
        ipv4_address: 172.20.0.3

networks:
  rhcsa-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
