services:
  backend:
    container_name: rhcsa-backend
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      PROXMOX_USER: "${PROXMOX_USER}"
      PROXMOX_PASSWORD: "${PROXMOX_PASSWORD}"
      TEMPLATE1: "${TEMPLATE1}"
      TEMPLATE2: "${TEMPLATE2}"
      TEMPLATE3: "${TEMPLATE3}"
    networks:
      rhcsa-net:
        ipv4_address: 172.20.0.2

  frontend:
    container_name: rhcsa-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      rhcsa-net:
        ipv4_address: 172.20.0.3

networks:
  rhcsa-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
